spring:
    application:
        name: notifictaion-service
    mail:
        host: localhost
        password: password
        port: 1025
        properties:
            mail:
                smtp:
                    auth: false
                    starttls:
                        enable: false
        username: sender@test.com
    
channels:
    slack:
        webhook-url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
    discord:
        webhook-url: https://discord.com/api/webhooks/000000000000000000/
