spring:
    application:
        name: notifictaion-service
    mail:
        host: localhost
        password: password
        port: 1025
        properties:
            mail:
                smtp:
                    auth: false
                    starttls:
                        enable: false
        username: sender@test.com
    data:
        mongodb:
           uri: mongodb://mongo:27017
           database: notification-service

channels:
    slack:
        webhook-url: https://hooks.slack.com/services/
    discord:
        webhook-url: https://discord.com/api/webhooks/
